color: null
description: null
fieldLayouts:
  fbd459f9-c8d2-42a1-9112-8ae3878f3df4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-28T03:50:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cd2b6320-a88c-4936-a31e-81a741d2281e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-28T03:52:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c3b0874-1048-4f1e-8133-3f2d651eb37b # Channels
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a59331c-fccd-41b8-ad95-6ea873fdadfd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b7aab5a-56a9-4d71-a1b6-0e78516234c8
        userCondition: null
handle: listing
hasTitleField: true
icon: list
name: 'Listing Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
