color: null
description: null
fieldLayouts:
  1bba52dd-253a-470a-972f-a7669950a1fc:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:82b7648e-6577-4ec6-b49c-42675ef4c23e'
      - 'layoutElement:d23d6e92-669c-4ea9-a913-124ec7c9f5f7'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-27T02:34:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fc138b4f-7406-4d6d-8f9c-df1bba8d3762
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-27T02:36:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a9b52af2-d6a8-44b8-8158-9d3be52a0d3b # Plain Text
            handle: role
            includeInCards: true
            instructions: null
            label: Role
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d23d6e92-669c-4ea9-a913-124ec7c9f5f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-27T02:36:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 68006928-9abf-4f12-aca6-5a03b6d6e672 # Text
            handle: bio
            includeInCards: false
            instructions: null
            label: Bio
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9e7eea2-cac7-41f7-8e0b-395ffab391c5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-27T02:36:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6996b9dd-5274-4574-8603-ffe2aee14e21 # Asset
            handle: image
            includeInCards: true
            instructions: null
            label: Image
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82b7648e-6577-4ec6-b49c-42675ef4c23e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9f859f2-a2b6-4fb8-95c7-4312226dd147
        userCondition: null
handle: person
hasTitleField: true
icon: null
name: Person
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
