color: null
description: 'A longform piece of content.'
fieldLayouts:
  70428863-2365-41d4-a275-3c3e1e579dd7:
    cardThumbAlignment: end
    cardView:
      - postDate
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-28T02:35:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b9809b09-754f-4ac3-8119-2e5e82aa8359
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-28T14:31:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 68006928-9abf-4f12-aca6-5a03b6d6e672 # Text
            handle: description
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afb72198-8334-4f7d-b58e-3aa1edef834c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-28T02:47:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2935cdea-e46e-4878-b568-f0e098ec2a4f # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae3488b4-fd80-4228-be80-9630ba7440d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-28T02:47:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4e561f16-ec34-404b-aff8-9759d01bb5c1 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da4638a9-37aa-4bf3-b765-4c47c8acc548
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d628660-6529-4f96-af9c-44e6118c10c5
        userCondition: null
handle: post
hasTitleField: true
icon: file-lines
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
