headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Full
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - underline
  - subscript
  - superscript
  - link
  - blockQuote
  - bulletedList
  - numberedList
  - insertTable
