baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Craft CMS Vite Tailwind'
primary: true
siteGroup: 45a00e92-2550-47ce-b789-33064e5da296 # Craft CMS Vite Tailwind
sortOrder: 1
