dateModified: 1761618485
email:
  fromEmail: hello@ambrosiaspace.com
  fromName: 'Ambrosia Space Manufacturing Corporation'
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: m/images
    type: craft\fs\Local
    url: /m/images
meta:
  __names__:
    1d209306-01a4-4dc7-bc72-da0723fee5aa: Header # Header
    4e561f16-ec34-404b-aff8-9759d01bb5c1: 'Rich Text' # Rich Text
    6fdfbe08-3bed-49e1-806c-1ae77457186d: Pages # Pages
    07bb3e53-0436-4795-8747-6138f3960508: 'Link List' # Link List
    45a00e92-2550-47ce-b789-33064e5da296: Ambrosia # Ambrosia
    46c73757-35e7-4b10-b847-51ab5433328d: Hyperlink # Hyperlink
    54f64a1d-1fa2-4197-aa96-6c979d97fcc6: Page # Page
    63e81627-f42b-495e-a7c7-6f4e42efdc35: Image # Image
    72c3451a-3b3b-46c5-ac75-dfcefb6fa165: Home # Home
    88a82adb-74b9-4d14-b4bf-8e9a26d20d3e: 'Ambrosia Space Manufacturing Company' # Ambrosia Space Manufacturing Company
    88af5f23-f761-4800-94d6-875a43403279: Simple # Simple
    89af2a35-e134-4f85-a55c-244e847bbb71: Full # Full
    98e1c883-e4bb-4f43-b092-59d0bf6b3bc8: People # People
    190a6916-6a81-4626-a188-9c9e95a060c2: 'People Listing' # People Listing
    703d0ba8-0c19-40a0-badf-501c9c9c54f2: Position # Position
    712e2ee5-eb54-4224-b7a1-fc87c8832892: Lightswitch # Lightswitch
    851aa807-5042-4526-a6a9-1a107ba6ce66: Grid # Grid
    970e9afc-e436-4f65-8d88-106a3bfbda43: 'Lightswitch (Default Off)' # Lightswitch (Default Off)
    2935cdea-e46e-4878-b568-f0e098ec2a4f: Image # Image
    6996b9dd-5274-4574-8603-ffe2aee14e21: Asset # Asset
    8344a3e0-212e-43cf-abb1-e1ffaaa22221: Small # Small
    9326f3fe-85dc-4d36-be66-51893eefcd06: 'Decorator Type' # Decorator Type
    490807f9-8e12-43ce-8fee-22730b42f3b4: Person # Person
    68006928-9abf-4f12-aca6-5a03b6d6e672: Text # Text
    a9b52af2-d6a8-44b8-8158-9d3be52a0d3b: 'Plain Text' # Plain Text
    a64c2e37-18b3-4179-b91c-72ded09fadb4: 'Grid Items' # Grid Items
    a173ce04-99ac-482e-a83c-6f2f39cbc6d3: Full # Full
    a315ebc2-7989-48ae-85e3-d0cb12a22440: 'Link List Item' # Link List Item
    b0f092c9-4cd7-4c5d-be70-089782fd85dd: Modules # Modules
    b2c03297-44b8-40b1-82cd-001bf51011e8: Feature # Feature
    c20da1f2-432b-4f57-a5df-412d795323e0: Assets # Assets
    e2b96770-e496-40d4-9d40-ef0d10c51ffa: Images # Images
    e527ad7b-f272-4e6d-97c6-ab32252afa11: 'Big Text' # Big Text
    e32214a7-85d3-48e4-94c3-3aec995098d1: 'Grid Item' # Grid Item
    e8458783-3f6a-43e3-8b85-f6b6ec9c2974: 'Top Decorator' # Top Decorator
    f6b01801-37c0-4e3f-ad44-20d619226d7d: 'Bottom Decorator' # Bottom Decorator
    f8f44cc1-2ad4-406c-b5ee-6f9f213c5501: 'Small Square' # Small Square
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Ambrosia Space Manufacturing Company'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
