dateModified: 1740581214
email:
  fromEmail: ryan@craftquest.io
  fromName: 'Craft CMS Vite Tailwind'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    45a00e92-2550-47ce-b789-33064e5da296: 'Craft CMS Vite Tailwind' # Craft CMS Vite Tailwind
    88a82adb-74b9-4d14-b4bf-8e9a26d20d3e: 'Craft CMS Vite Tailwind' # Craft CMS Vite Tailwind
system:
  edition: solo
  live: true
  name: 'Craft CMS Vite Tailwind'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
