fieldLayouts:
  0118b056-8973-4a2b-9ea5-9a1554ee3179:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-27T20:05:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 07bb3e53-0436-4795-8747-6138f3960508 # Link List
            handle: navigation
            includeInCards: false
            instructions: null
            label: Navigation
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 062b35a1-6351-4bc9-ab94-384583513ab6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59cca3ec-9ec5-4ac8-8996-0c06313f310c
        userCondition: null
handle: header
name: Header
sortOrder: 1
