defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e25bf06d-bad3-4352-bf56-44988e8e77fd # Post
handle: updates
maxAuthors: null
name: Updates
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  88a82adb-74b9-4d14-b4bf-8e9a26d20d3e: # Ambrosia Space Manufacturing Company
    enabledByDefault: true
    hasUrls: true
    template: entry.twig
    uriFormat: 'updates/{slug}'
type: channel
